---
title: "Exploratory Plots"
output: html_notebook
---

Read in data.
```{r}
setwd("/projects/sbrown_prj/POG/immunoPOG/analysis/mutPepBind/immunoPOG19_170815/")

minpep <- read.table("peptideIDs.tsv", header=T, stringsAsFactors = F, sep ="\t")
pmhc <- read.table("immunoPOG19_pMHC_parsed.tsv", header = T, stringsAsFactors = F, sep = "\t")
```

Join together to track lost mutations (mutation didn't generate a novel sequence)
```{r}
minpep <- minpep[,1:7]

dat <- merge(minpep[,c("tumour","minPeptideID","ENST","mutation","varPos","pepSequence")], pmhc, by.x=c("tumour","ENST","mutation"), by.y=c("barcode","ENST","mutation"), all.x=T)
```


Get sample-level stats
```{r}
sumdat <- do.call(rbind, by(dat, dat$tumour, function(x){
  numMut <- length(unique(paste(x[["ENST"]], x[["mutation"]])))
  numPMHC <- nrow(x)
  numSNV_pmhc <- sum(grepl("SNV",x[["mutation"]]))
  numINDEL_pmhc <- sum(grepl("INDEL",x[["mutation"]]))
  binding <- subset(x, as.numeric(x[["mut_ic50"]]) < 500)
  numPMHC_bind <- nrow(binding)
  numSNV_pmhc_bind <- sum(grepl("SNV",binding$mutation))
  numINDEL_pmhc_bind <- sum(grepl("INDEL",binding$mutation))
  
  return(data.frame(sample=x[["tumour"]][1],
                    numMut = numMut,
                    numPMHC = numPMHC,
                    numSNV_pmhc = numSNV_pmhc,
                    numINDEL_pmhc = numINDEL_pmhc,
                    numPMHC_bind = numPMHC_bind,
                    numSNV_pmhc_bind = numSNV_pmhc_bind,
                    numINDEL_pmhc_bind = numINDEL_pmhc_bind))
}))
```


Number of mutations per sample
```{r}
ggplot(sumdat, aes(y=sample, x=numMut)) + geom_point() + theme_bw()
```

Number of PMHC vs num MUT
```{r}
ggplot(sumdat, aes(x=numMut, y=numPMHC, label=sample)) + geom_point() + geom_text_repel(force=5) + theme_bw()
```

Number of SNV pmhc vs num indel pmhc
```{r}
ggplot(sumdat, aes(x=numSNV_pmhc, y=numINDEL_pmhc, label=sample)) + geom_point() + geom_text_repel(force=5) + theme_bw()
```

Number of SNV binders vs num indel binders
```{r}
ggplot(sumdat, aes(x=numSNV_pmhc_bind, y=numINDEL_pmhc_bind, label=sample)) + geom_point() + geom_text_repel(force=5) + theme_bw()
```